version: '3'
services:
  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ../common/mysql/:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        limits:
          memory: 512M
  keycloak:
    image: jboss/keycloak:8.0.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8080
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    command:
#      - "-Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/data/data.json"
      - "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/data/data.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    volumes:
      - ../common/keycloak/:/opt/data/
    ports:
      - 4000:8080
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 512M
  redis:
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 512M
  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ../common/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ../common/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    deploy:
      resources:
        limits:
          memory: 256M